const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8').replaceAll('\r\n', '\n');
const order = JSON.parse(read('src/content-order.json'));
const core = ['timing.mjs', 'lrc.mjs', 'readings.mjs'].map(file =>
  '// Core: ' + file + '\n' + read('src/core/' + file).replace(/^export (?=function )/gm, '')
).join('\n');
const parts = order.map(file => {
  if (!/^[a-z-]+\.js$/.test(file)) throw Error('Invalid source name: ' + file);
  return '// Feature: ' + file + '\n' + read('src/content/' + file);
}).join('\n');
const output = '// GENERATED by npm run build — edit src/, not this file.\n(function () {\n"use strict";\n' + core + '\n' + parts + '\n})();\n';
new vm.Script(output, { filename: 'content.js' });
if (process.argv.includes('--check')) {
  if (read('content.js') !== output) { console.error('content.js is stale. Run npm run build.'); process.exitCode = 1; }
} else {
  fs.writeFileSync(path.join(root, 'content.js'), output);
  console.log('Built content.js from ' + order.length + ' feature sources and 3 core modules.');
}
